# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 1) do

  create_table "commands", :primary_key => "command_id", :force => true do |t|
    t.integer  "grd_id"
    t.integer  "output_number", :default => 0,     :null => false
    t.boolean  "state",         :default => false, :null => false
    t.datetime "date",                             :null => false
  end

  create_table "configuraciones", :force => true do |t|
    t.string "atributo"
    t.string "valor"
  end

  create_table "historical", :primary_key => "historial_id", :force => true do |t|
    t.integer   "grd_id",          :null => false
    t.integer   "register_type",   :null => false
    t.datetime  "timestamp",       :null => false
    t.integer   "address",         :null => false
    t.integer   "value",           :null => false
    t.integer   "historical_type"
    t.timestamp "insertion_time",  :null => false
  end

  create_table "reports", :primary_key => "grd_id", :force => true do |t|
    t.integer  "state", :default => 0,     :null => false
    t.boolean  "i1",    :default => false, :null => false
    t.boolean  "i2",    :default => false, :null => false
    t.boolean  "i3",    :default => false, :null => false
    t.boolean  "i4",    :default => false, :null => false
    t.boolean  "i5",    :default => false, :null => false
    t.boolean  "i6",    :default => false, :null => false
    t.boolean  "i7",    :default => false, :null => false
    t.boolean  "i8",    :default => false, :null => false
    t.boolean  "i9",    :default => false, :null => false
    t.boolean  "i10",   :default => false, :null => false
    t.boolean  "i11",   :default => false, :null => false
    t.boolean  "i12",   :default => false, :null => false
    t.boolean  "i13",   :default => false, :null => false
    t.boolean  "i14",   :default => false, :null => false
    t.boolean  "i15",   :default => false, :null => false
    t.boolean  "i16",   :default => false, :null => false
    t.boolean  "i17",   :default => false, :null => false
    t.boolean  "i18",   :default => false, :null => false
    t.boolean  "i19",   :default => false, :null => false
    t.boolean  "i20",   :default => false, :null => false
    t.boolean  "i21",   :default => false, :null => false
    t.boolean  "i22",   :default => false, :null => false
    t.boolean  "i23",   :default => false, :null => false
    t.boolean  "i24",   :default => false, :null => false
    t.boolean  "i25",   :default => false, :null => false
    t.boolean  "i26",   :default => false, :null => false
    t.boolean  "i27",   :default => false, :null => false
    t.boolean  "i28",   :default => false, :null => false
    t.boolean  "i29",   :default => false, :null => false
    t.boolean  "i30",   :default => false, :null => false
    t.boolean  "i31",   :default => false, :null => false
    t.boolean  "i32",   :default => false, :null => false
    t.boolean  "i33",   :default => false, :null => false
    t.boolean  "i34",   :default => false, :null => false
    t.boolean  "i35",   :default => false, :null => false
    t.boolean  "i36",   :default => false, :null => false
    t.boolean  "i37",   :default => false, :null => false
    t.boolean  "i38",   :default => false, :null => false
    t.boolean  "i39",   :default => false, :null => false
    t.boolean  "i40",   :default => false, :null => false
    t.boolean  "i41",   :default => false, :null => false
    t.boolean  "i42",   :default => false, :null => false
    t.boolean  "i43",   :default => false, :null => false
    t.boolean  "i44",   :default => false, :null => false
    t.boolean  "i45",   :default => false, :null => false
    t.boolean  "i46",   :default => false, :null => false
    t.boolean  "i47",   :default => false, :null => false
    t.boolean  "i48",   :default => false, :null => false
    t.boolean  "i49",   :default => false, :null => false
    t.boolean  "i50",   :default => false, :null => false
    t.boolean  "i51",   :default => false, :null => false
    t.boolean  "i52",   :default => false, :null => false
    t.boolean  "i53",   :default => false, :null => false
    t.boolean  "i54",   :default => false, :null => false
    t.boolean  "i55",   :default => false, :null => false
    t.boolean  "i56",   :default => false, :null => false
    t.boolean  "i57",   :default => false, :null => false
    t.boolean  "i58",   :default => false, :null => false
    t.boolean  "i59",   :default => false, :null => false
    t.boolean  "i60",   :default => false, :null => false
    t.boolean  "i61",   :default => false, :null => false
    t.boolean  "i62",   :default => false, :null => false
    t.boolean  "i63",   :default => false, :null => false
    t.boolean  "i64",   :default => false, :null => false
    t.boolean  "i65",   :default => false, :null => false
    t.boolean  "i66",   :default => false, :null => false
    t.boolean  "i67",   :default => false, :null => false
    t.boolean  "i68",   :default => false, :null => false
    t.boolean  "i69",   :default => false, :null => false
    t.boolean  "i70",   :default => false, :null => false
    t.boolean  "i71",   :default => false, :null => false
    t.boolean  "i72",   :default => false, :null => false
    t.boolean  "i73",   :default => false, :null => false
    t.boolean  "i74",   :default => false, :null => false
    t.boolean  "i75",   :default => false, :null => false
    t.boolean  "i76",   :default => false, :null => false
    t.boolean  "i77",   :default => false, :null => false
    t.boolean  "i78",   :default => false, :null => false
    t.boolean  "i79",   :default => false, :null => false
    t.boolean  "i80",   :default => false, :null => false
    t.boolean  "i81",   :default => false, :null => false
    t.boolean  "i82",   :default => false, :null => false
    t.boolean  "i83",   :default => false, :null => false
    t.boolean  "i84",   :default => false, :null => false
    t.boolean  "i85",   :default => false, :null => false
    t.boolean  "i86",   :default => false, :null => false
    t.boolean  "i87",   :default => false, :null => false
    t.boolean  "i88",   :default => false, :null => false
    t.boolean  "i89",   :default => false, :null => false
    t.boolean  "i90",   :default => false, :null => false
    t.boolean  "i91",   :default => false, :null => false
    t.boolean  "i92",   :default => false, :null => false
    t.boolean  "i93",   :default => false, :null => false
    t.boolean  "i94",   :default => false, :null => false
    t.boolean  "i95",   :default => false, :null => false
    t.boolean  "i96",   :default => false, :null => false
    t.boolean  "i97",   :default => false, :null => false
    t.boolean  "i98",   :default => false, :null => false
    t.boolean  "i99",   :default => false, :null => false
    t.boolean  "i100",  :default => false, :null => false
    t.boolean  "i101",  :default => false, :null => false
    t.boolean  "i102",  :default => false, :null => false
    t.boolean  "i103",  :default => false, :null => false
    t.boolean  "i104",  :default => false, :null => false
    t.boolean  "i105",  :default => false, :null => false
    t.boolean  "i106",  :default => false, :null => false
    t.boolean  "i107",  :default => false, :null => false
    t.boolean  "i108",  :default => false, :null => false
    t.boolean  "i109",  :default => false, :null => false
    t.boolean  "i110",  :default => false, :null => false
    t.boolean  "i111",  :default => false, :null => false
    t.boolean  "i112",  :default => false, :null => false
    t.boolean  "i113",  :default => false, :null => false
    t.boolean  "i114",  :default => false, :null => false
    t.boolean  "i115",  :default => false, :null => false
    t.boolean  "i116",  :default => false, :null => false
    t.boolean  "i117",  :default => false, :null => false
    t.boolean  "i118",  :default => false, :null => false
    t.boolean  "i119",  :default => false, :null => false
    t.boolean  "i120",  :default => false, :null => false
    t.boolean  "i121",  :default => false, :null => false
    t.boolean  "i122",  :default => false, :null => false
    t.boolean  "i123",  :default => false, :null => false
    t.boolean  "i124",  :default => false, :null => false
    t.boolean  "i125",  :default => false, :null => false
    t.boolean  "i126",  :default => false, :null => false
    t.boolean  "i127",  :default => false, :null => false
    t.boolean  "i128",  :default => false, :null => false
    t.boolean  "i129",  :default => false, :null => false
    t.boolean  "i130",  :default => false, :null => false
    t.boolean  "i131",  :default => false, :null => false
    t.boolean  "i132",  :default => false, :null => false
    t.boolean  "i133",  :default => false, :null => false
    t.boolean  "i134",  :default => false, :null => false
    t.boolean  "i135",  :default => false, :null => false
    t.boolean  "i136",  :default => false, :null => false
    t.boolean  "i137",  :default => false, :null => false
    t.boolean  "i138",  :default => false, :null => false
    t.boolean  "i139",  :default => false, :null => false
    t.boolean  "i140",  :default => false, :null => false
    t.boolean  "i141",  :default => false, :null => false
    t.boolean  "i142",  :default => false, :null => false
    t.boolean  "i143",  :default => false, :null => false
    t.boolean  "i144",  :default => false, :null => false
    t.boolean  "i145",  :default => false, :null => false
    t.boolean  "i146",  :default => false, :null => false
    t.boolean  "i147",  :default => false, :null => false
    t.boolean  "i148",  :default => false, :null => false
    t.boolean  "i149",  :default => false, :null => false
    t.boolean  "i150",  :default => false, :null => false
    t.boolean  "i151",  :default => false, :null => false
    t.boolean  "i152",  :default => false, :null => false
    t.boolean  "i153",  :default => false, :null => false
    t.boolean  "i154",  :default => false, :null => false
    t.boolean  "i155",  :default => false, :null => false
    t.boolean  "i156",  :default => false, :null => false
    t.boolean  "i157",  :default => false, :null => false
    t.boolean  "i158",  :default => false, :null => false
    t.boolean  "i159",  :default => false, :null => false
    t.boolean  "i160",  :default => false, :null => false
    t.boolean  "i161",  :default => false, :null => false
    t.boolean  "i162",  :default => false, :null => false
    t.boolean  "i163",  :default => false, :null => false
    t.boolean  "i164",  :default => false, :null => false
    t.boolean  "i165",  :default => false, :null => false
    t.boolean  "i166",  :default => false, :null => false
    t.boolean  "i167",  :default => false, :null => false
    t.boolean  "i168",  :default => false, :null => false
    t.boolean  "i169",  :default => false, :null => false
    t.boolean  "i170",  :default => false, :null => false
    t.boolean  "i171",  :default => false, :null => false
    t.boolean  "i172",  :default => false, :null => false
    t.boolean  "i173",  :default => false, :null => false
    t.boolean  "i174",  :default => false, :null => false
    t.boolean  "i175",  :default => false, :null => false
    t.boolean  "i176",  :default => false, :null => false
    t.boolean  "i177",  :default => false, :null => false
    t.boolean  "i178",  :default => false, :null => false
    t.boolean  "i179",  :default => false, :null => false
    t.boolean  "i180",  :default => false, :null => false
    t.boolean  "i181",  :default => false, :null => false
    t.boolean  "i182",  :default => false, :null => false
    t.boolean  "i183",  :default => false, :null => false
    t.boolean  "i184",  :default => false, :null => false
    t.boolean  "i185",  :default => false, :null => false
    t.boolean  "i186",  :default => false, :null => false
    t.boolean  "i187",  :default => false, :null => false
    t.boolean  "i188",  :default => false, :null => false
    t.boolean  "i189",  :default => false, :null => false
    t.boolean  "i190",  :default => false, :null => false
    t.boolean  "i191",  :default => false, :null => false
    t.boolean  "i192",  :default => false, :null => false
    t.boolean  "i193",  :default => false, :null => false
    t.boolean  "i194",  :default => false, :null => false
    t.boolean  "i195",  :default => false, :null => false
    t.boolean  "i196",  :default => false, :null => false
    t.boolean  "i197",  :default => false, :null => false
    t.boolean  "i198",  :default => false, :null => false
    t.boolean  "i199",  :default => false, :null => false
    t.boolean  "i200",  :default => false, :null => false
    t.boolean  "o1",    :default => false, :null => false
    t.boolean  "o2",    :default => false, :null => false
    t.boolean  "o3",    :default => false, :null => false
    t.boolean  "o4",    :default => false, :null => false
    t.boolean  "o5",    :default => false, :null => false
    t.boolean  "o6",    :default => false, :null => false
    t.boolean  "o7",    :default => false, :null => false
    t.boolean  "o8",    :default => false, :null => false
    t.boolean  "o9",    :default => false, :null => false
    t.boolean  "o10",   :default => false, :null => false
    t.boolean  "o11",   :default => false, :null => false
    t.boolean  "o12",   :default => false, :null => false
    t.boolean  "o13",   :default => false, :null => false
    t.boolean  "o14",   :default => false, :null => false
    t.boolean  "o15",   :default => false, :null => false
    t.boolean  "o16",   :default => false, :null => false
    t.boolean  "o17",   :default => false, :null => false
    t.boolean  "o18",   :default => false, :null => false
    t.boolean  "o19",   :default => false, :null => false
    t.boolean  "o20",   :default => false, :null => false
    t.boolean  "o21",   :default => false, :null => false
    t.boolean  "o22",   :default => false, :null => false
    t.boolean  "o23",   :default => false, :null => false
    t.boolean  "o24",   :default => false, :null => false
    t.boolean  "o25",   :default => false, :null => false
    t.boolean  "o26",   :default => false, :null => false
    t.boolean  "o27",   :default => false, :null => false
    t.boolean  "o28",   :default => false, :null => false
    t.boolean  "o29",   :default => false, :null => false
    t.boolean  "o30",   :default => false, :null => false
    t.boolean  "o31",   :default => false, :null => false
    t.boolean  "o32",   :default => false, :null => false
    t.boolean  "o33",   :default => false, :null => false
    t.boolean  "o34",   :default => false, :null => false
    t.boolean  "o35",   :default => false, :null => false
    t.boolean  "o36",   :default => false, :null => false
    t.boolean  "o37",   :default => false, :null => false
    t.boolean  "o38",   :default => false, :null => false
    t.boolean  "o39",   :default => false, :null => false
    t.boolean  "o40",   :default => false, :null => false
    t.boolean  "o41",   :default => false, :null => false
    t.boolean  "o42",   :default => false, :null => false
    t.boolean  "o43",   :default => false, :null => false
    t.boolean  "o44",   :default => false, :null => false
    t.boolean  "o45",   :default => false, :null => false
    t.boolean  "o46",   :default => false, :null => false
    t.boolean  "o47",   :default => false, :null => false
    t.boolean  "o48",   :default => false, :null => false
    t.boolean  "o49",   :default => false, :null => false
    t.boolean  "o50",   :default => false, :null => false
    t.boolean  "o51",   :default => false, :null => false
    t.boolean  "o52",   :default => false, :null => false
    t.boolean  "o53",   :default => false, :null => false
    t.boolean  "o54",   :default => false, :null => false
    t.boolean  "o55",   :default => false, :null => false
    t.boolean  "o56",   :default => false, :null => false
    t.boolean  "o57",   :default => false, :null => false
    t.boolean  "o58",   :default => false, :null => false
    t.boolean  "o59",   :default => false, :null => false
    t.boolean  "o60",   :default => false, :null => false
    t.boolean  "o61",   :default => false, :null => false
    t.boolean  "o62",   :default => false, :null => false
    t.boolean  "o63",   :default => false, :null => false
    t.boolean  "o64",   :default => false, :null => false
    t.boolean  "o65",   :default => false, :null => false
    t.boolean  "o66",   :default => false, :null => false
    t.boolean  "o67",   :default => false, :null => false
    t.boolean  "o68",   :default => false, :null => false
    t.boolean  "o69",   :default => false, :null => false
    t.boolean  "o70",   :default => false, :null => false
    t.boolean  "o71",   :default => false, :null => false
    t.boolean  "o72",   :default => false, :null => false
    t.boolean  "o73",   :default => false, :null => false
    t.boolean  "o74",   :default => false, :null => false
    t.boolean  "o75",   :default => false, :null => false
    t.boolean  "o76",   :default => false, :null => false
    t.boolean  "o77",   :default => false, :null => false
    t.boolean  "o78",   :default => false, :null => false
    t.boolean  "o79",   :default => false, :null => false
    t.boolean  "o80",   :default => false, :null => false
    t.boolean  "o81",   :default => false, :null => false
    t.boolean  "o82",   :default => false, :null => false
    t.boolean  "o83",   :default => false, :null => false
    t.boolean  "o84",   :default => false, :null => false
    t.boolean  "o85",   :default => false, :null => false
    t.boolean  "o86",   :default => false, :null => false
    t.boolean  "o87",   :default => false, :null => false
    t.boolean  "o88",   :default => false, :null => false
    t.boolean  "o89",   :default => false, :null => false
    t.boolean  "o90",   :default => false, :null => false
    t.boolean  "o91",   :default => false, :null => false
    t.boolean  "o92",   :default => false, :null => false
    t.boolean  "o93",   :default => false, :null => false
    t.boolean  "o94",   :default => false, :null => false
    t.boolean  "o95",   :default => false, :null => false
    t.boolean  "o96",   :default => false, :null => false
    t.boolean  "o97",   :default => false, :null => false
    t.boolean  "o98",   :default => false, :null => false
    t.boolean  "o99",   :default => false, :null => false
    t.boolean  "o100",  :default => false, :null => false
    t.boolean  "o101",  :default => false, :null => false
    t.boolean  "o102",  :default => false, :null => false
    t.boolean  "o103",  :default => false, :null => false
    t.boolean  "o104",  :default => false, :null => false
    t.boolean  "o105",  :default => false, :null => false
    t.boolean  "o106",  :default => false, :null => false
    t.boolean  "o107",  :default => false, :null => false
    t.boolean  "o108",  :default => false, :null => false
    t.boolean  "o109",  :default => false, :null => false
    t.boolean  "o110",  :default => false, :null => false
    t.boolean  "o111",  :default => false, :null => false
    t.boolean  "o112",  :default => false, :null => false
    t.boolean  "o113",  :default => false, :null => false
    t.boolean  "o114",  :default => false, :null => false
    t.boolean  "o115",  :default => false, :null => false
    t.boolean  "o116",  :default => false, :null => false
    t.boolean  "o117",  :default => false, :null => false
    t.boolean  "o118",  :default => false, :null => false
    t.boolean  "o119",  :default => false, :null => false
    t.boolean  "o120",  :default => false, :null => false
    t.boolean  "o121",  :default => false, :null => false
    t.boolean  "o122",  :default => false, :null => false
    t.boolean  "o123",  :default => false, :null => false
    t.boolean  "o124",  :default => false, :null => false
    t.boolean  "o125",  :default => false, :null => false
    t.boolean  "o126",  :default => false, :null => false
    t.boolean  "o127",  :default => false, :null => false
    t.boolean  "o128",  :default => false, :null => false
    t.boolean  "o129",  :default => false, :null => false
    t.boolean  "o130",  :default => false, :null => false
    t.boolean  "o131",  :default => false, :null => false
    t.boolean  "o132",  :default => false, :null => false
    t.boolean  "o133",  :default => false, :null => false
    t.boolean  "o134",  :default => false, :null => false
    t.boolean  "o135",  :default => false, :null => false
    t.boolean  "o136",  :default => false, :null => false
    t.boolean  "o137",  :default => false, :null => false
    t.boolean  "o138",  :default => false, :null => false
    t.boolean  "o139",  :default => false, :null => false
    t.boolean  "o140",  :default => false, :null => false
    t.boolean  "o141",  :default => false, :null => false
    t.boolean  "o142",  :default => false, :null => false
    t.boolean  "o143",  :default => false, :null => false
    t.boolean  "o144",  :default => false, :null => false
    t.boolean  "o145",  :default => false, :null => false
    t.boolean  "o146",  :default => false, :null => false
    t.boolean  "o147",  :default => false, :null => false
    t.boolean  "o148",  :default => false, :null => false
    t.boolean  "o149",  :default => false, :null => false
    t.boolean  "o150",  :default => false, :null => false
    t.boolean  "o151",  :default => false, :null => false
    t.boolean  "o152",  :default => false, :null => false
    t.boolean  "o153",  :default => false, :null => false
    t.boolean  "o154",  :default => false, :null => false
    t.boolean  "o155",  :default => false, :null => false
    t.boolean  "o156",  :default => false, :null => false
    t.boolean  "o157",  :default => false, :null => false
    t.boolean  "o158",  :default => false, :null => false
    t.boolean  "o159",  :default => false, :null => false
    t.boolean  "o160",  :default => false, :null => false
    t.boolean  "o161",  :default => false, :null => false
    t.boolean  "o162",  :default => false, :null => false
    t.boolean  "o163",  :default => false, :null => false
    t.boolean  "o164",  :default => false, :null => false
    t.boolean  "o165",  :default => false, :null => false
    t.boolean  "o166",  :default => false, :null => false
    t.boolean  "o167",  :default => false, :null => false
    t.boolean  "o168",  :default => false, :null => false
    t.boolean  "o169",  :default => false, :null => false
    t.boolean  "o170",  :default => false, :null => false
    t.boolean  "o171",  :default => false, :null => false
    t.boolean  "o172",  :default => false, :null => false
    t.boolean  "o173",  :default => false, :null => false
    t.boolean  "o174",  :default => false, :null => false
    t.boolean  "o175",  :default => false, :null => false
    t.boolean  "o176",  :default => false, :null => false
    t.boolean  "o177",  :default => false, :null => false
    t.boolean  "o178",  :default => false, :null => false
    t.boolean  "o179",  :default => false, :null => false
    t.boolean  "o180",  :default => false, :null => false
    t.boolean  "o181",  :default => false, :null => false
    t.boolean  "o182",  :default => false, :null => false
    t.boolean  "o183",  :default => false, :null => false
    t.boolean  "o184",  :default => false, :null => false
    t.boolean  "o185",  :default => false, :null => false
    t.boolean  "o186",  :default => false, :null => false
    t.boolean  "o187",  :default => false, :null => false
    t.boolean  "o188",  :default => false, :null => false
    t.boolean  "o189",  :default => false, :null => false
    t.boolean  "o190",  :default => false, :null => false
    t.boolean  "o191",  :default => false, :null => false
    t.boolean  "o192",  :default => false, :null => false
    t.boolean  "o193",  :default => false, :null => false
    t.boolean  "o194",  :default => false, :null => false
    t.boolean  "o195",  :default => false, :null => false
    t.boolean  "o196",  :default => false, :null => false
    t.boolean  "o197",  :default => false, :null => false
    t.boolean  "o198",  :default => false, :null => false
    t.boolean  "o199",  :default => false, :null => false
    t.boolean  "o200",  :default => false, :null => false
    t.integer  "an1",   :default => 0,     :null => false
    t.integer  "an2",   :default => 0,     :null => false
    t.integer  "an3",   :default => 0,     :null => false
    t.integer  "an4",   :default => 0,     :null => false
    t.integer  "an5",   :default => 0,     :null => false
    t.integer  "an6",   :default => 0,     :null => false
    t.integer  "an7",   :default => 0,     :null => false
    t.integer  "an8",   :default => 0,     :null => false
    t.integer  "an9",   :default => 0,     :null => false
    t.integer  "an10",  :default => 0,     :null => false
    t.integer  "an11",  :default => 0,     :null => false
    t.integer  "an12",  :default => 0,     :null => false
    t.integer  "an13",  :default => 0,     :null => false
    t.integer  "an14",  :default => 0,     :null => false
    t.integer  "an15",  :default => 0,     :null => false
    t.integer  "an16",  :default => 0,     :null => false
    t.integer  "an17",  :default => 0,     :null => false
    t.integer  "an18",  :default => 0,     :null => false
    t.integer  "an19",  :default => 0,     :null => false
    t.integer  "an20",  :default => 0,     :null => false
    t.integer  "an21",  :default => 0,     :null => false
    t.integer  "an22",  :default => 0,     :null => false
    t.integer  "an23",  :default => 0,     :null => false
    t.integer  "an24",  :default => 0,     :null => false
    t.integer  "an25",  :default => 0,     :null => false
    t.integer  "an26",  :default => 0,     :null => false
    t.integer  "an27",  :default => 0,     :null => false
    t.integer  "an28",  :default => 0,     :null => false
    t.integer  "an29",  :default => 0,     :null => false
    t.integer  "an30",  :default => 0,     :null => false
    t.integer  "an31",  :default => 0,     :null => false
    t.integer  "an32",  :default => 0,     :null => false
    t.integer  "an33",  :default => 0,     :null => false
    t.integer  "an34",  :default => 0,     :null => false
    t.integer  "an35",  :default => 0,     :null => false
    t.integer  "an36",  :default => 0,     :null => false
    t.integer  "an37",  :default => 0,     :null => false
    t.integer  "an38",  :default => 0,     :null => false
    t.integer  "an39",  :default => 0,     :null => false
    t.integer  "an40",  :default => 0,     :null => false
    t.integer  "an41",  :default => 0,     :null => false
    t.integer  "an42",  :default => 0,     :null => false
    t.integer  "an43",  :default => 0,     :null => false
    t.integer  "an44",  :default => 0,     :null => false
    t.integer  "an45",  :default => 0,     :null => false
    t.integer  "an46",  :default => 0,     :null => false
    t.integer  "an47",  :default => 0,     :null => false
    t.integer  "an48",  :default => 0,     :null => false
    t.integer  "an49",  :default => 0,     :null => false
    t.integer  "an50",  :default => 0,     :null => false
    t.integer  "an51",  :default => 0,     :null => false
    t.integer  "an52",  :default => 0,     :null => false
    t.integer  "an53",  :default => 0,     :null => false
    t.integer  "an54",  :default => 0,     :null => false
    t.integer  "an55",  :default => 0,     :null => false
    t.integer  "an56",  :default => 0,     :null => false
    t.integer  "an57",  :default => 0,     :null => false
    t.integer  "an58",  :default => 0,     :null => false
    t.integer  "an59",  :default => 0,     :null => false
    t.integer  "an60",  :default => 0,     :null => false
    t.integer  "an61",  :default => 0,     :null => false
    t.integer  "an62",  :default => 0,     :null => false
    t.integer  "an63",  :default => 0,     :null => false
    t.integer  "an64",  :default => 0,     :null => false
    t.integer  "an65",  :default => 0,     :null => false
    t.integer  "an66",  :default => 0,     :null => false
    t.integer  "an67",  :default => 0,     :null => false
    t.integer  "an68",  :default => 0,     :null => false
    t.integer  "an69",  :default => 0,     :null => false
    t.integer  "an70",  :default => 0,     :null => false
    t.integer  "an71",  :default => 0,     :null => false
    t.integer  "an72",  :default => 0,     :null => false
    t.integer  "an73",  :default => 0,     :null => false
    t.integer  "an74",  :default => 0,     :null => false
    t.integer  "an75",  :default => 0,     :null => false
    t.integer  "an76",  :default => 0,     :null => false
    t.integer  "an77",  :default => 0,     :null => false
    t.integer  "an78",  :default => 0,     :null => false
    t.integer  "an79",  :default => 0,     :null => false
    t.integer  "an80",  :default => 0,     :null => false
    t.integer  "an81",  :default => 0,     :null => false
    t.integer  "an82",  :default => 0,     :null => false
    t.integer  "an83",  :default => 0,     :null => false
    t.integer  "an84",  :default => 0,     :null => false
    t.integer  "an85",  :default => 0,     :null => false
    t.integer  "an86",  :default => 0,     :null => false
    t.integer  "an87",  :default => 0,     :null => false
    t.integer  "an88",  :default => 0,     :null => false
    t.integer  "an89",  :default => 0,     :null => false
    t.integer  "an90",  :default => 0,     :null => false
    t.integer  "an91",  :default => 0,     :null => false
    t.integer  "an92",  :default => 0,     :null => false
    t.integer  "an93",  :default => 0,     :null => false
    t.integer  "an94",  :default => 0,     :null => false
    t.integer  "an95",  :default => 0,     :null => false
    t.integer  "an96",  :default => 0,     :null => false
    t.integer  "an97",  :default => 0,     :null => false
    t.integer  "an98",  :default => 0,     :null => false
    t.integer  "an99",  :default => 0,     :null => false
    t.integer  "an100", :default => 0,     :null => false
    t.integer  "an101", :default => 0,     :null => false
    t.integer  "an102", :default => 0,     :null => false
    t.integer  "an103", :default => 0,     :null => false
    t.integer  "an104", :default => 0,     :null => false
    t.integer  "an105", :default => 0,     :null => false
    t.integer  "an106", :default => 0,     :null => false
    t.integer  "an107", :default => 0,     :null => false
    t.integer  "an108", :default => 0,     :null => false
    t.integer  "an109", :default => 0,     :null => false
    t.integer  "an110", :default => 0,     :null => false
    t.integer  "an111", :default => 0,     :null => false
    t.integer  "an112", :default => 0,     :null => false
    t.integer  "an113", :default => 0,     :null => false
    t.integer  "an114", :default => 0,     :null => false
    t.integer  "an115", :default => 0,     :null => false
    t.integer  "an116", :default => 0,     :null => false
    t.integer  "an117", :default => 0,     :null => false
    t.integer  "an118", :default => 0,     :null => false
    t.integer  "an119", :default => 0,     :null => false
    t.integer  "an120", :default => 0,     :null => false
    t.integer  "an121", :default => 0,     :null => false
    t.integer  "an122", :default => 0,     :null => false
    t.integer  "an123", :default => 0,     :null => false
    t.integer  "an124", :default => 0,     :null => false
    t.integer  "an125", :default => 0,     :null => false
    t.integer  "an126", :default => 0,     :null => false
    t.integer  "an127", :default => 0,     :null => false
    t.integer  "an128", :default => 0,     :null => false
    t.integer  "an129", :default => 0,     :null => false
    t.integer  "an130", :default => 0,     :null => false
    t.integer  "an131", :default => 0,     :null => false
    t.integer  "an132", :default => 0,     :null => false
    t.integer  "an133", :default => 0,     :null => false
    t.integer  "an134", :default => 0,     :null => false
    t.integer  "an135", :default => 0,     :null => false
    t.integer  "an136", :default => 0,     :null => false
    t.integer  "an137", :default => 0,     :null => false
    t.integer  "an138", :default => 0,     :null => false
    t.integer  "an139", :default => 0,     :null => false
    t.integer  "an140", :default => 0,     :null => false
    t.integer  "an141", :default => 0,     :null => false
    t.integer  "an142", :default => 0,     :null => false
    t.integer  "an143", :default => 0,     :null => false
    t.integer  "an144", :default => 0,     :null => false
    t.integer  "an145", :default => 0,     :null => false
    t.integer  "an146", :default => 0,     :null => false
    t.integer  "an147", :default => 0,     :null => false
    t.integer  "an148", :default => 0,     :null => false
    t.integer  "an149", :default => 0,     :null => false
    t.integer  "an150", :default => 0,     :null => false
    t.integer  "an151", :default => 0,     :null => false
    t.integer  "an152", :default => 0,     :null => false
    t.integer  "an153", :default => 0,     :null => false
    t.integer  "an154", :default => 0,     :null => false
    t.integer  "an155", :default => 0,     :null => false
    t.integer  "an156", :default => 0,     :null => false
    t.integer  "an157", :default => 0,     :null => false
    t.integer  "an158", :default => 0,     :null => false
    t.integer  "an159", :default => 0,     :null => false
    t.integer  "an160", :default => 0,     :null => false
    t.integer  "an161", :default => 0,     :null => false
    t.integer  "an162", :default => 0,     :null => false
    t.integer  "an163", :default => 0,     :null => false
    t.integer  "an164", :default => 0,     :null => false
    t.integer  "an165", :default => 0,     :null => false
    t.integer  "an166", :default => 0,     :null => false
    t.integer  "an167", :default => 0,     :null => false
    t.integer  "an168", :default => 0,     :null => false
    t.integer  "an169", :default => 0,     :null => false
    t.integer  "an170", :default => 0,     :null => false
    t.integer  "an171", :default => 0,     :null => false
    t.integer  "an172", :default => 0,     :null => false
    t.integer  "an173", :default => 0,     :null => false
    t.integer  "an174", :default => 0,     :null => false
    t.integer  "an175", :default => 0,     :null => false
    t.integer  "an176", :default => 0,     :null => false
    t.integer  "an177", :default => 0,     :null => false
    t.integer  "an178", :default => 0,     :null => false
    t.integer  "an179", :default => 0,     :null => false
    t.integer  "an180", :default => 0,     :null => false
    t.integer  "an181", :default => 0,     :null => false
    t.integer  "an182", :default => 0,     :null => false
    t.integer  "an183", :default => 0,     :null => false
    t.integer  "an184", :default => 0,     :null => false
    t.integer  "an185", :default => 0,     :null => false
    t.integer  "an186", :default => 0,     :null => false
    t.integer  "an187", :default => 0,     :null => false
    t.integer  "an188", :default => 0,     :null => false
    t.integer  "an189", :default => 0,     :null => false
    t.integer  "an190", :default => 0,     :null => false
    t.integer  "an191", :default => 0,     :null => false
    t.integer  "an192", :default => 0,     :null => false
    t.integer  "an193", :default => 0,     :null => false
    t.integer  "an194", :default => 0,     :null => false
    t.integer  "an195", :default => 0,     :null => false
    t.integer  "an196", :default => 0,     :null => false
    t.integer  "an197", :default => 0,     :null => false
    t.integer  "an198", :default => 0,     :null => false
    t.integer  "an199", :default => 0,     :null => false
    t.integer  "an200", :default => 0,     :null => false
    t.integer  "p1",    :default => 0,     :null => false
    t.integer  "p2",    :default => 0,     :null => false
    t.integer  "p3",    :default => 0,     :null => false
    t.integer  "p4",    :default => 0,     :null => false
    t.integer  "p5",    :default => 0,     :null => false
    t.integer  "p6",    :default => 0,     :null => false
    t.integer  "p7",    :default => 0,     :null => false
    t.integer  "p8",    :default => 0,     :null => false
    t.integer  "p9",    :default => 0,     :null => false
    t.integer  "p10",   :default => 0,     :null => false
    t.integer  "p11",   :default => 0,     :null => false
    t.integer  "p12",   :default => 0,     :null => false
    t.integer  "p13",   :default => 0,     :null => false
    t.integer  "p14",   :default => 0,     :null => false
    t.integer  "p15",   :default => 0,     :null => false
    t.integer  "p16",   :default => 0,     :null => false
    t.integer  "p17",   :default => 0,     :null => false
    t.integer  "p18",   :default => 0,     :null => false
    t.integer  "p19",   :default => 0,     :null => false
    t.integer  "p20",   :default => 0,     :null => false
    t.integer  "p21",   :default => 0,     :null => false
    t.integer  "p22",   :default => 0,     :null => false
    t.integer  "p23",   :default => 0,     :null => false
    t.integer  "p24",   :default => 0,     :null => false
    t.integer  "p25",   :default => 0,     :null => false
    t.integer  "p26",   :default => 0,     :null => false
    t.integer  "p27",   :default => 0,     :null => false
    t.integer  "p28",   :default => 0,     :null => false
    t.integer  "p29",   :default => 0,     :null => false
    t.integer  "p30",   :default => 0,     :null => false
    t.integer  "p31",   :default => 0,     :null => false
    t.integer  "p32",   :default => 0,     :null => false
    t.integer  "p33",   :default => 0,     :null => false
    t.integer  "p34",   :default => 0,     :null => false
    t.integer  "p35",   :default => 0,     :null => false
    t.integer  "p36",   :default => 0,     :null => false
    t.integer  "p37",   :default => 0,     :null => false
    t.integer  "p38",   :default => 0,     :null => false
    t.integer  "p39",   :default => 0,     :null => false
    t.integer  "p40",   :default => 0,     :null => false
    t.integer  "p41",   :default => 0,     :null => false
    t.integer  "p42",   :default => 0,     :null => false
    t.integer  "p43",   :default => 0,     :null => false
    t.integer  "p44",   :default => 0,     :null => false
    t.integer  "p45",   :default => 0,     :null => false
    t.integer  "p46",   :default => 0,     :null => false
    t.integer  "p47",   :default => 0,     :null => false
    t.integer  "p48",   :default => 0,     :null => false
    t.integer  "p49",   :default => 0,     :null => false
    t.integer  "p50",   :default => 0,     :null => false
    t.integer  "p51",   :default => 0,     :null => false
    t.integer  "p52",   :default => 0,     :null => false
    t.integer  "p53",   :default => 0,     :null => false
    t.integer  "p54",   :default => 0,     :null => false
    t.integer  "p55",   :default => 0,     :null => false
    t.integer  "p56",   :default => 0,     :null => false
    t.integer  "p57",   :default => 0,     :null => false
    t.integer  "p58",   :default => 0,     :null => false
    t.integer  "p59",   :default => 0,     :null => false
    t.integer  "p60",   :default => 0,     :null => false
    t.integer  "p61",   :default => 0,     :null => false
    t.integer  "p62",   :default => 0,     :null => false
    t.integer  "p63",   :default => 0,     :null => false
    t.integer  "p64",   :default => 0,     :null => false
    t.integer  "p65",   :default => 0,     :null => false
    t.integer  "p66",   :default => 0,     :null => false
    t.integer  "p67",   :default => 0,     :null => false
    t.integer  "p68",   :default => 0,     :null => false
    t.integer  "p69",   :default => 0,     :null => false
    t.integer  "p70",   :default => 0,     :null => false
    t.integer  "p71",   :default => 0,     :null => false
    t.integer  "p72",   :default => 0,     :null => false
    t.integer  "p73",   :default => 0,     :null => false
    t.integer  "p74",   :default => 0,     :null => false
    t.integer  "p75",   :default => 0,     :null => false
    t.integer  "p76",   :default => 0,     :null => false
    t.integer  "p77",   :default => 0,     :null => false
    t.integer  "p78",   :default => 0,     :null => false
    t.integer  "p79",   :default => 0,     :null => false
    t.integer  "p80",   :default => 0,     :null => false
    t.integer  "p81",   :default => 0,     :null => false
    t.integer  "p82",   :default => 0,     :null => false
    t.integer  "p83",   :default => 0,     :null => false
    t.integer  "p84",   :default => 0,     :null => false
    t.integer  "p85",   :default => 0,     :null => false
    t.integer  "p86",   :default => 0,     :null => false
    t.integer  "p87",   :default => 0,     :null => false
    t.integer  "p88",   :default => 0,     :null => false
    t.integer  "p89",   :default => 0,     :null => false
    t.integer  "p90",   :default => 0,     :null => false
    t.integer  "p91",   :default => 0,     :null => false
    t.integer  "p92",   :default => 0,     :null => false
    t.integer  "p93",   :default => 0,     :null => false
    t.integer  "p94",   :default => 0,     :null => false
    t.integer  "p95",   :default => 0,     :null => false
    t.integer  "p96",   :default => 0,     :null => false
    t.integer  "p97",   :default => 0,     :null => false
    t.integer  "p98",   :default => 0,     :null => false
    t.integer  "p99",   :default => 0,     :null => false
    t.integer  "p100",  :default => 0,     :null => false
    t.integer  "p101",  :default => 0,     :null => false
    t.integer  "p102",  :default => 0,     :null => false
    t.integer  "p103",  :default => 0,     :null => false
    t.integer  "p104",  :default => 0,     :null => false
    t.integer  "p105",  :default => 0,     :null => false
    t.integer  "p106",  :default => 0,     :null => false
    t.integer  "p107",  :default => 0,     :null => false
    t.integer  "p108",  :default => 0,     :null => false
    t.integer  "p109",  :default => 0,     :null => false
    t.integer  "p110",  :default => 0,     :null => false
    t.integer  "p111",  :default => 0,     :null => false
    t.integer  "p112",  :default => 0,     :null => false
    t.integer  "p113",  :default => 0,     :null => false
    t.integer  "p114",  :default => 0,     :null => false
    t.integer  "p115",  :default => 0,     :null => false
    t.integer  "p116",  :default => 0,     :null => false
    t.integer  "p117",  :default => 0,     :null => false
    t.integer  "p118",  :default => 0,     :null => false
    t.integer  "p119",  :default => 0,     :null => false
    t.integer  "p120",  :default => 0,     :null => false
    t.integer  "p121",  :default => 0,     :null => false
    t.integer  "p122",  :default => 0,     :null => false
    t.integer  "p123",  :default => 0,     :null => false
    t.integer  "p124",  :default => 0,     :null => false
    t.integer  "p125",  :default => 0,     :null => false
    t.integer  "p126",  :default => 0,     :null => false
    t.integer  "p127",  :default => 0,     :null => false
    t.integer  "p128",  :default => 0,     :null => false
    t.integer  "p129",  :default => 0,     :null => false
    t.integer  "p130",  :default => 0,     :null => false
    t.integer  "p131",  :default => 0,     :null => false
    t.integer  "p132",  :default => 0,     :null => false
    t.integer  "p133",  :default => 0,     :null => false
    t.integer  "p134",  :default => 0,     :null => false
    t.integer  "p135",  :default => 0,     :null => false
    t.integer  "p136",  :default => 0,     :null => false
    t.integer  "p137",  :default => 0,     :null => false
    t.integer  "p138",  :default => 0,     :null => false
    t.integer  "p139",  :default => 0,     :null => false
    t.integer  "p140",  :default => 0,     :null => false
    t.integer  "p141",  :default => 0,     :null => false
    t.integer  "p142",  :default => 0,     :null => false
    t.integer  "p143",  :default => 0,     :null => false
    t.integer  "p144",  :default => 0,     :null => false
    t.integer  "p145",  :default => 0,     :null => false
    t.integer  "p146",  :default => 0,     :null => false
    t.integer  "p147",  :default => 0,     :null => false
    t.integer  "p148",  :default => 0,     :null => false
    t.integer  "p149",  :default => 0,     :null => false
    t.integer  "p150",  :default => 0,     :null => false
    t.integer  "p151",  :default => 0,     :null => false
    t.integer  "p152",  :default => 0,     :null => false
    t.integer  "p153",  :default => 0,     :null => false
    t.integer  "p154",  :default => 0,     :null => false
    t.integer  "p155",  :default => 0,     :null => false
    t.integer  "p156",  :default => 0,     :null => false
    t.integer  "p157",  :default => 0,     :null => false
    t.integer  "p158",  :default => 0,     :null => false
    t.integer  "p159",  :default => 0,     :null => false
    t.integer  "p160",  :default => 0,     :null => false
    t.integer  "p161",  :default => 0,     :null => false
    t.integer  "p162",  :default => 0,     :null => false
    t.integer  "p163",  :default => 0,     :null => false
    t.integer  "p164",  :default => 0,     :null => false
    t.integer  "p165",  :default => 0,     :null => false
    t.integer  "p166",  :default => 0,     :null => false
    t.integer  "p167",  :default => 0,     :null => false
    t.integer  "p168",  :default => 0,     :null => false
    t.integer  "p169",  :default => 0,     :null => false
    t.integer  "p170",  :default => 0,     :null => false
    t.integer  "p171",  :default => 0,     :null => false
    t.integer  "p172",  :default => 0,     :null => false
    t.integer  "p173",  :default => 0,     :null => false
    t.integer  "p174",  :default => 0,     :null => false
    t.integer  "p175",  :default => 0,     :null => false
    t.integer  "p176",  :default => 0,     :null => false
    t.integer  "p177",  :default => 0,     :null => false
    t.integer  "p178",  :default => 0,     :null => false
    t.integer  "p179",  :default => 0,     :null => false
    t.integer  "p180",  :default => 0,     :null => false
    t.integer  "p181",  :default => 0,     :null => false
    t.integer  "p182",  :default => 0,     :null => false
    t.integer  "p183",  :default => 0,     :null => false
    t.integer  "p184",  :default => 0,     :null => false
    t.integer  "p185",  :default => 0,     :null => false
    t.integer  "p186",  :default => 0,     :null => false
    t.integer  "p187",  :default => 0,     :null => false
    t.integer  "p188",  :default => 0,     :null => false
    t.integer  "p189",  :default => 0,     :null => false
    t.integer  "p190",  :default => 0,     :null => false
    t.integer  "p191",  :default => 0,     :null => false
    t.integer  "p192",  :default => 0,     :null => false
    t.integer  "p193",  :default => 0,     :null => false
    t.integer  "p194",  :default => 0,     :null => false
    t.integer  "p195",  :default => 0,     :null => false
    t.integer  "p196",  :default => 0,     :null => false
    t.integer  "p197",  :default => 0,     :null => false
    t.integer  "p198",  :default => 0,     :null => false
    t.integer  "p199",  :default => 0,     :null => false
    t.integer  "p200",  :default => 0,     :null => false
    t.datetime "date"
  end

end
